In [1]:
from google.colab import files
 
 
uploaded = files.upload()

Saving Iris.csv to Iris.csv


In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("Iris.csv")

In [4]:
df.head(5)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [5]:
df.tail(5)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica

In [6]:
df.dtypes

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

In [7]:
df.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [9]:
df.max()

Id                          150
SepalLengthCm               7.9
SepalWidthCm                4.4
PetalLengthCm               6.9
PetalWidthCm                2.5
Species          Iris-virginica
dtype: object

In [11]:
df.shape

(150, 6)

In [12]:
df.size

900

In [10]:
df.min()

Id                         1
SepalLengthCm            4.3
SepalWidthCm             2.0
PetalLengthCm            1.0
PetalWidthCm             0.1
Species          Iris-setosa
dtype: object

In [14]:
df.isna().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [34]:
X = df.iloc[:,1:5]
print(X) 

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]


In [35]:
Y = df.iloc[:,-1]

In [23]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.33,random_state=42)

In [24]:
from sklearn.naive_bayes import GaussianNB
sc = GaussianNB().fit(X_train,Y_train)


In [27]:
from sklearn.metrics import confusion_matrix,accuracy_score
y_test_pred = sc.predict(X_test)
print(Y)
print(y_test_pred)


0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object
['Iris-versicolor' 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-virginica'
 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica'
 'Iris-setosa' 'Iris-virginica' 'Iris-setosa' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-setosa' 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-virginica'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa'

In [28]:
cm1 = confusion_matrix(Y_test,y_test_pred)
print(cm1)
acc = accuracy_score(Y_test,y_test_pred)
print(acc)

[[19  0  0]
 [ 0 14  1]
 [ 0  1 15]]
0.96


In [30]:

#for setosa class
tp = cm1[0][0]
fn = cm1[0][1] + cm1[0][2]
fp = cm1[1][0] + cm1[2][0]
tn = cm1[1][1] + cm1[1][2] + cm1[2][1] + cm1[2][2]
total = tp+fp+tn+fn
print('Error rate:')
error= (fp+fn)/total
print(error)

Error rate:
0.0


In [31]:
#for Versicolor
tp = cm1[1][1]
fn = cm1[1][0]+cm1[1][2]
fp = cm1[0][1] + cm1[2][1]
tn = cm1[0][0] + cm1[0][2] + cm1[2][0] + cm1[2][2]
total = tp+fn+fp+tn
print('Error rate:')
error = (fp+fn)/total
print(error)

Error rate:
0.04


In [32]:
#for Virginica
tp = cm1[2][2]
fn = cm1[2][0] + cm1[2][1]
fp = cm1[0][2] + cm1[1][2]
tn = cm1[0][0] + cm1[0][1] + cm1[1][0] +cm1[1][1]
total = tp+fn+fp+tn
print('Error rate:')
error = (fp+fn)/total
print(error)

Error rate:
0.04


In [33]:
from sklearn.metrics import classification_report
print('                     Classification Report:')
print(' ')
print(classification_report(Y_test,y_test_pred))

                     Classification Report:
 
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        19
Iris-versicolor       0.93      0.93      0.93        15
 Iris-virginica       0.94      0.94      0.94        16

       accuracy                           0.96        50
      macro avg       0.96      0.96      0.96        50
   weighted avg       0.96      0.96      0.96        50

